lambda_0_3:
    general: *general_base
    planner:
      <<: *planner_base
      lambda: 0.3
    executor: *executor_base
    verifier: *verifier_base
  lambda_0_5:
    <<: *base_template           
  lambda_0_7:
    general: *general_base
    planner:
      <<: *planner_base
      lambda: 0.7
    executor: *executor_base
    verifier: *verifier_base

# Exp 2 – Pipeline variants
  random_planning:
    general: *general_base
    planner:
      <<: *planner_base
      enable: false
      optimize_pipeline: false   # Disable planning
    executor: *executor_base
    verifier: *verifier_base

  planned_no_optimisation:
    general: *general_base
    planner:
      <<: *planner_base
      enable: true
      optimize_pipeline: false   # Use detected order, no search
    executor: *executor_base
    verifier: *verifier_base

  planned_opt_no_verify:
    general:
      <<: *general_base
      max_retries: 1             # Single pass
    planner: *planner_base
    executor: *executor_base
    verifier:
      enable: true              # Skip verification

  planned_opt_with_verify:
    <<: *base_template

  # Exp 1 – Varying λ during pipeline optimisation
  lambda_0:
    general: *general_base
    planner:
      <<: *planner_base
      lambda: 0
    executor: *executor_base
    verifier: *verifier_base

  finetuned_planned_opt_verify:
    general: *general_base
    planner:
      <<: *planner_base
      lambda: 0.7
    executor: *executor_base
    verifier: *verifier_base